// Code generated by "stringer -type=QuestionType -trimprefix=QuestionType"; DO NOT EDIT.

package forms

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[QuestionTypeSeparator-0]
	_ = x[QuestionTypeText-1]
	_ = x[QuestionTypeTextArea-2]
	_ = x[QuestionTypeCheckbox-3]
	_ = x[QuestionTypeRadio-4]
	_ = x[QuestionTypeSelect-5]
}

const _QuestionType_name = "SeparatorTextTextAreaCheckboxRadioSelect"

var _QuestionType_index = [...]uint8{0, 9, 13, 21, 29, 34, 40}

func (i QuestionType) String() string {
	if i >= QuestionType(len(_QuestionType_index)-1) {
		return "QuestionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _QuestionType_name[_QuestionType_index[i]:_QuestionType_index[i+1]]
}
